apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: my-nginx-pod
      labels:
        app: nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
