apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf
  labels:
    app: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.2.2\"]"
    spec:
      containers:
        - name: amf
          securityContext:
            privileged: true
          image: free5gc-build:v3.0.5
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["-c", "./bin/amf"]
          volumeMounts:
            - name: amf-config
              mountPath: /root/free5gc/config/amfcfg.yaml
              subPath: amfcfg.yaml
      volumes:
        - name: amf-config
          configMap:
            name: amf
