apiVersion: apps/v1
kind: Deployment
metadata:
  name: nssf
  labels:
    app: nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nssf
  template:
    metadata:
      labels:
        app: nssf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.2.5\"]"
    spec:
      containers:
        - name: nssf
          image: free5gc-build:v3.0.5
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["-c", "./bin/nssf"]
          stdin: true
          tty: true
          volumeMounts:
            - name: nssf-config
              mountPath: /root/free5gc/config/nssfcfg.yaml
              subPath: nssfcfg.yaml
      volumes:
        - name: nssf-config
          configMap:
            name: nssf
